# Dockerfile (backend)
FROM node:18-slim


RUN apt-get update && \
    apt-get install -y libreoffice curl gnupg && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
    
WORKDIR /app

COPY package*.json ./

# Cài nodemon toàn cục
RUN npm install -g nodemon

# Cài deps trong dự án
RUN npm install

COPY . .

EXPOSE 5000

CMD ["nodemon", "app.js"]
